// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHcnGS4Jm6J2dmwOWAJ-gqYc-VHVilgIg',
    appId: '1:903799597617:web:7b58f3b91e3d7946ad8310',
    messagingSenderId: '903799597617',
    projectId: 'shine-on-rent',
    authDomain: 'shine-on-rent.firebaseapp.com',
    storageBucket: 'shine-on-rent.appspot.com',
    measurementId: 'G-DKY2FN04H2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIalXbLTeItfikxD1EYF2OmCzJihBEmR8',
    appId: '1:903799597617:android:e158ce9d297a3965ad8310',
    messagingSenderId: '903799597617',
    projectId: 'shine-on-rent',
    storageBucket: 'shine-on-rent.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHcnGS4Jm6J2dmwOWAJ-gqYc-VHVilgIg',
    appId: '1:903799597617:web:58e10f0f5525da5dad8310',
    messagingSenderId: '903799597617',
    projectId: 'shine-on-rent',
    authDomain: 'shine-on-rent.firebaseapp.com',
    storageBucket: 'shine-on-rent.appspot.com',
    measurementId: 'G-WWF5EB0E0P',
  );
}
